// *** FEED TYPES ***
export const LOAD_FEED = 'LOAD_FEED'
export const LOAD_FEED_EXAMPLE = 'LOAD_FEED_EXAMPLE'
export const SET_FEED_DATA = 'SET_FEED_DATA'
export const SET_FEED_FILTERED_DATA = 'SET_FEED_FILTERED_DATA'
export const SET_FILTERS_TYPE = 'SET_FILTERS_TYPE'
export const SET_FEED_COUNT = 'SET_FEED_COUNT'
export const SET_FEED_SELECTED_CARD = 'SET_FEED_SELECTED_CARD'
export const SET_FEED_AVERAGE_PRICE = 'SET_FEED_AVERAGE_PRICE'
export const SET_FEED_AVERAGE_PPSM = 'SET_FEED_AVERAGE_PPSM'
export const FILTER_FEED_DATA = 'FILTER_FEED_DATA'
export const SET_FILTERS_CHANGED = 'SET_FILTERS_CHANGED'
export const SET_FEED_LOADING = 'SET_FEED_LOADING'
export const SET_FEED_LOADING_FAILED = 'SET_FEED_LOADING_FAILED'
export const SET_BLOCK = 'SET_BLOCK'

// *** FILTERS TYPES ***
export const LOAD_FILTERS = 'LOAD_FILTERS'
export const SET_FILTERS_LOADING = 'SET_FILTERS_LOADING'
export const SET_FILTERS = 'SET_SALE_FILTERS'
export const SET_SUBURB = 'SET_SUBURB'
export const SET_PRICE_RANGE = 'SET_PRICE_RANGE'
export const SET_BEDROOMS = 'SET_BEDROOMS'
export const SET_BATHROOMS = 'SET_BATHROOMS'

// *** LISTING DETAILS TYPES ***
export const LOAD_LISTING_DETAILS = 'LOAD_LISTING_DETAILS'
export const SET_LISTING_DETAILS = 'SET_LISTING_DETAILS'
export const SET_LISTING_DETAILS_LOADING = 'SET_LISTING_DETAILS_LOADING'
export const SET_LISTING_DETAILS_LOADING_FAILED = 'SET_LISTING_DETAILS_LOADING_FAILED'

// *** USER TYPES ***
export const LOAD_USER_DETAILS = 'LOAD_USER_DETAILS'
export const SET_USER_DETAILS = 'SET_USER_DETAILS'
export const SET_USER_NEW_ANON = 'SET_USER_NEW_ANON'
export const SET_USER_DETAILS_LOADING = 'SET_USER_DETAILS_LOADING'
export const SET_USER_DETAILS_LOADING_FAILED = 'SET_USER_DETAILS_LOADING_FAILED'

// *** AUTH TYPES ***
export const AUTH_EMAIL_LOGIN = 'AUTH_EMAIL_PWORD_LOGIN'
export const AUTH_REGISTER = 'AUTH_REGISTER'
export const AUTH_GOOGLE_LOGIN = 'AUTH_GOOGLE_LOGIN'
export const AUTH_FACEBOOK = 'AUTH_FACEBOOK'
export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const LOAD_APP_DATA = 'LOAD_APP_DATA'
export const CREATE_ANONYMOUS_USER = 'CREATE_ANONYMOUS_USER'

// *** PAYMENT TYPES ***
export const REQUEST_SUBSCRIPTION = 'REQUEST_SUBSCRIPTION'
export const REQUEST_PAYMENT = 'REQUEST_PAYMENT'

// *** SCRAPING TYPES ***
export const GET_PAGE_HTML = 'GET_PAGE_HTML'
