const WIDTH_BREAKPOINT = 1000
const WIDTH_BREAKPOINT2 = 500

// *** CONSTANTS ***

const SALE_FILTER_PRICE_MIN = 0
const SALE_FILTER_PRICE_MAX = 100000000
const RENTAL_FILTER_PRICE_MIN = 0
const RENTAL_FILTER_PRICE_MAX = 100000
const MAX_DISTANCE_FROM_ME = 10
const MAX_BEDROOMS_AND_BATHROOMS = 10

export const constants = {
  SALE_FILTER_PRICE_MIN: SALE_FILTER_PRICE_MIN,
  SALE_FILTER_PRICE_MAX: SALE_FILTER_PRICE_MAX,
  RENTAL_FILTER_PRICE_MIN: RENTAL_FILTER_PRICE_MIN,
  RENTAL_FILTER_PRICE_MAX: RENTAL_FILTER_PRICE_MAX,
  MAX_DISTANCE_FROM_ME: MAX_DISTANCE_FROM_ME,
  MAX_BEDROOMS_AND_BATHROOMS: MAX_BEDROOMS_AND_BATHROOMS
}

// COLORS

const PRIMARY_COLOR = 'rgb(47,230,166)'
const PRIMARY_COLOR_SHADOW = 'rgb(40,186,145)'
const PRIMARY_COLOR_LIGHT = 'rgb(77,239,177)'
const PRIMARY_COLOR_OPACITY = 'rgba(47,230,166,0.3)'
const PRIMARY_COLOR_HEX = '#2fe6a6' // react-native-shadow only takes hex values
const SECONDARY_COLOR = 'rgb(47,137,128)'
const SECONDARY_COLOR_OPACITY = 'rgba(47,137,128,0.5)'
const SECONDARY_COLOR_DARK = 'rgb(34, 96, 102)'
const SECONDARY_COLOR_DARK_2 = 'rgb(15, 48, 44)'
const SECONDARY_COLOR_HEX = '#2f8980'
const DARK_COLOR = 'rgb(30, 20, 25)'
const BODY_TEXT_COLOR = 'rgb(152, 164, 185)'
const PLACE_HOLDER_TEXT_COLOR = 'rgb(200, 210, 220)'
const ERROR_TEXT_COLOR = 'rgb(240,50,50)'
const ACCENT_COLOR_1 = 'rgb(241,118,114)'
const ACCENT_COLOR_2 = 'rgb(255,204,136)'
const ACCENT_COLOR_1_SHADOW = 'rgb(198,99,92)'
const ACCENT_COLOR_2_SHADOW = 'rgb(193,152,108)'
const ACCENT_COLOR_1_HEX = '#f17672'
const ACCENT_COLOR_2_HEX = '#ffcc88'
const LIGHT_GREY = 'rgb(237,242,247)'
const MEDIUM_GREY = 'rgb(180,180,180)'
const DARK_GREY = 'rgb(50,50,50)'
const BORDER_COLOR = 'rgb(220,220,220)'

const IOS_BOX_SHADOW =
'0 3px 1px rgba(47,137,128,0.1),0 4px 8px rgba(15, 48, 44,0.2),0 0 0 1px rgba(47,137,128,0.05)'

const TOP_BAR_HEIGHT = 50

export const styleConstants = {
  PRIMARY_COLOR: PRIMARY_COLOR,
  PRIMARY_COLOR_SHADOW: PRIMARY_COLOR_SHADOW,
  PRIMARY_COLOR_LIGHT: PRIMARY_COLOR_LIGHT,
  PRIMARY_COLOR_OPACITY: PRIMARY_COLOR_OPACITY,
  PRIMARY_COLOR_HEX: PRIMARY_COLOR_HEX,
  SECONDARY_COLOR: SECONDARY_COLOR,
  SECONDARY_COLOR_OPACITY: SECONDARY_COLOR_OPACITY,
  SECONDARY_COLOR_DARK: SECONDARY_COLOR_DARK,
  SECONDARY_COLOR_DARK_2: SECONDARY_COLOR_DARK_2,
  SECONDARY_COLOR_HEX: SECONDARY_COLOR_HEX,
  DARK_COLOR: DARK_COLOR,
  BODY_TEXT_COLOR: BODY_TEXT_COLOR,
  PLACE_HOLDER_TEXT_COLOR: PLACE_HOLDER_TEXT_COLOR,
  ERROR_TEXT_COLOR: ERROR_TEXT_COLOR,
  ACCENT_COLOR_1: ACCENT_COLOR_1,
  ACCENT_COLOR_2: ACCENT_COLOR_2,
  ACCENT_COLOR_1_SHADOW: ACCENT_COLOR_1_SHADOW,
  ACCENT_COLOR_2_SHADOW: ACCENT_COLOR_2_SHADOW,
  ACCENT_COLOR_1_HEX: ACCENT_COLOR_1_HEX,
  ACCENT_COLOR_2_HEX: ACCENT_COLOR_2_HEX,
  LIGHT_GREY: LIGHT_GREY,
  MEDIUM_GREY: MEDIUM_GREY,
  DARK_GREY: DARK_GREY,
  BORDER_COLOR: BORDER_COLOR,
  WIDTH_BREAKPOINT: WIDTH_BREAKPOINT,
  WIDTH_BREAKPOINT2: WIDTH_BREAKPOINT2,
  IOS_BOX_SHADOW: IOS_BOX_SHADOW,
  TOP_BAR_HEIGHT: TOP_BAR_HEIGHT
}
